### ISSUE TITLE
dimension reduction 거친 결과를 Visualize

### ISSUE THREAD

**Issue by qlqhqo2341** [umbum/FDS2019#6]
- https://dash-gallery.plotly.host/dash-tsne/
- https://dash-gallery.plotly.host/dash-svm/

python Plotly로는 페이지 이동 없이 그래프 새로고침을 처리할 수 없음.
- dash를 사용할 것인가?
- plotly-js를 사용할 것인가?

dash가 비교적 작업 시간이 적게 걸릴 것 같아 dash로 작업. 하다가 문제 생기면 plotly-js로 변경하기로 함.

**Comment by umbum** [comment]
### t-SNE
발표자료 작성 시 참고
- https://ratsgo.github.io/machine%20learning/2017/04/28/tSNE/
- https://lovit.github.io/nlp/representation/2018/09/28/tsne/
- https://dash-gallery.plotly.host/dash-tsne/ - Learn More 클릭해서 나오는 설명들.
- https://bcho.tistory.com/1210

**Comment by umbum** [comment]
done in 1692abec4d66c8e9027f3d7e078a8dd9dcaf21a3
